### ISSUE TITLE
Time does not reset when closing neovim

### ISSUE THREAD

**Issue by atemmel** [aurieh/discord.nvim#11]
Upon an unexpected shutdown of my computer, the plugin keeps collecting time for whatever reason. Previously, it'd reset its timer after closing the current file. Running `:DiscordUpdatePrescence` does not change anything, nor does reinstalling the plugin.
![image](https://user-images.githubusercontent.com/33461151/48942382-85a4e100-ef1f-11e8-88d3-558433d525c5.png)

**Comment by aurieh** [comment]
I don't think I can do anything about this behavior, it's something the Discord client handles.

**Comment by atemmel** [comment]
I see. Any suggestions as for things I could try on my end to solve this issue? I've tried reinstalling discord as well as nuking the `.config` directory.

**Comment by ObserverOfTime** [comment]
Try applying this patch. Discord seems to mess up when the timestamp isn't an integer.
```patch
diff --git a/rplugin/python3/discord/__init__.py b/rplugin/python3/discord/__init__.py
index 383ccc1..bbe67ce 100644
--- a/rplugin/python3/discord/__init__.py
+++ b/rplugin/python3/discord/__init__.py
@@ -107,7 +107,7 @@ class DiscordPlugin(object):
             "large_text": "The One True Editor",
             "large_image": "neovim"
         }
-        activity["timestamps"] = {"start": time()}
+        activity["timestamps"] = {"start": int(time())}
         if ft:
             if len(ft) == 1:
                 ft = "lang_{}".format(ft)
```

**Comment by aurieh** [comment]
@ObserverOfTime if that works, please make a PR. It's truly amazing how inconsistent Discord can be.

**Comment by ObserverOfTime** [comment]
Define `reinstalling the now modified plugin`.
The patch hasn't been committed, you have to apply it manually.

**Comment by atemmel** [comment]
Fair enough.
I opened the `discord.nvim/rplugin/python3/discord/__init__.py` file with neovim and wrapped the `time()` call with an `int` cast. Nothing seemed to have changed in the behaviour of the plugin, so I removed it from my `.vimrc` and ran `:VundleClean`. I then exited neovim and started it again, this time adding the plugin to my `.vimrc`. I restarted the program once more, this time running `:VundleInstall` and then `:VundleUpdate`. The plugin was now 'working', minus the way it chose to count time. I then repeated this process with all calls to `time()` but nothing changed.

**Comment by ObserverOfTime** [comment]
Perhaps Vundle overwrote the changes? If that's not the case, then I don't know. It works for me at least.

**Comment by atemmel** [comment]
I just opened the file and all my casts are still there. :/

**Comment by ObserverOfTime** [comment]
You can try my [persistent-timer](/ObserverOfTime/discord.nvim/tree/persistent-timer) branch. It handles the timer differently which *might* fix this issue.

**Comment by ObserverOfTime** [comment]
The `persistent-timer` branch uses the same images as this. My fork's default `refactored` branch has many changes including new images. If Vundle doesn't allow you to specify a branch, you can either use a different plugin manager, or manually checkout `persistent-timer`.

I can also PR `persistent-timer` here if @aurieh approves.

**Comment by aurieh** [comment]
@ObserverOfTime sure!
