### ISSUE TITLE
PermissionError: Operation not permitted: '/tmp/dnvim_lock'

### ISSUE THREAD

**Issue by Cyber28** [aurieh/discord.nvim#16]
```error caught in async handler '/home/cyber28/.config/nvim/plugged/discord.nvim/rplugin/python3/discord:autocmd:BufEnter:* []'
Traceback (most recent call last):
  File "/home/cyber28/.config/nvim/plugged/discord.nvim/rplugin/python3/discord/__init__.py", line 54, in on_bufenter
    self.update_presence()
  File "/home/cyber28/.config/nvim/plugged/discord.nvim/rplugin/python3/discord/__init__.py", line 74, in update_presence
    self.locked = not self.lock.lock()
  File "/home/cyber28/.config/nvim/plugged/discord.nvim/rplugin/python3/discord/pidlock.py", line 17, in lock
    if not self.unlock():
  File "/home/cyber28/.config/nvim/plugged/discord.nvim/rplugin/python3/discord/pidlock.py", line 33, in unlock
    remove(self.path)
PermissionError: [Errno 1] Operation not permitted: '/tmp/dnvim_lock'```

Launching with sudo says that local discord client isn't found.
I tried reinstalling both the plugin and neovim entirely, but no luck.

**Comment by aurieh** [comment]
What is the output of `stat /tmp`?

**Comment by Cyber28** [comment]
I'm running nvim as cyber28, a regular account.
Output of `stat /tmp`
  File: /tmp
  Size: 69632     	Blocks: 144        IO Block: 4096   directory
Device: 816h/2070d	Inode: 3801089     Links: 19
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-05-11 16:30:01.266951555 +0200
Modify: 2019-05-14 20:00:14.002058439 +0200
Change: 2019-05-14 20:00:14.002058439 +0200
 Birth: -```

**Comment by aurieh** [comment]
Do you by any chance have a leftover `dnvim_lock` from running nvim as a different user? If so, remove it.

**Comment by Cyber28** [comment]
I did have a `dnvim_lock` file,  but after deleting it the issue still occurs

**Comment by ObserverOfTime** [comment]
`$XDG_RUNTIME_DIR` is set to `/run/$UID` in most Linux distros and could be used to avoid ownership issues. It's also where Discord stores its socket file by default. Though, if the issue occurs even after deleting the file, this probably isn't due to the ownership.

**Comment by aurieh** [comment]
Yeah, we should probably change the lock file dir to `XDG_RUNTIME_DIR`. That said, this definitely seems like a filesystem permission issue, not anything to do with the project.
