### ISSUE TITLE
Doesn't work sometimes

### ISSUE THREAD

**Issue by Jerrynicki** [aurieh/discord.nvim#18]
I sometimes get these errors

```
no notification handler registered for "/home/niklas/.local/share/nvim/plugged/discord.nvim/rplugin/python3/discord:autocmd:BufEnter:*"
no notification handler registered for "/home/niklas/.local/share/nvim/plugged/discord.nvim/rplugin/python3/discord:autocmd:VimEnter:*"
```

after starting Neovim with discord.nvim installed. When these errors appear, there's also no rich presence shown on Discord. They seem to appear randomly, also on files where the rich presence worked just a few minutes before.

**Comment by aurieh** [comment]
You didn't install the plugin properly. What plugin manager did you use and have you tried running `:UpdateRemotePlugins`?

**Comment by DrBluefall** [comment]
I'm getting the same issue as well. I used Pathogen to install the plugin, and I made sure to do `:UpdateRemotePlugins` *immediately* after installation. Even then, it didn't work.

**Comment by DrBluefall** [comment]
I'm having the same issue as well. I used Pathogen to install the plugin as a git submodule, and made sure to do `:UpdateRemotePlugins` *immediately* after install. Even then, it didn't work.

**Comment by jcarter777** [comment]
just installed and this is still an issue

**Comment by aurieh** [comment]
Probably an issue with python-neovim on certain systems/configurations, as I don't use any special hooks or anything of that sort. I'll look into this but can't promise anything.
