### ISSUE TITLE
Not updating on startup

### ISSUE THREAD

**Issue by nitsuga5124** [aurieh/discord.nvim#19]
https://pastebin.com/98iwEfp3 

discord.nvim is not triggering on startup, even though i have it set to 1 in L76 and the other variables on top and bottom work fine.

I can make it work with `:DiscordUpdatePresence` but that's tedious to do every time.

**Comment by aurieh** [comment]
Could you please try reproducing this with a minimal vimrc?

**Comment by nitsuga5124** [comment]
`autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endifA`
Is the cause, commenting it makes it work. Not sure what on it is causing it.

**Comment by ObserverOfTime** [comment]
Change `endifA` to `endif`.
