### ISSUE TITLE
uninstalling with plug seems to have missed something

### ISSUE THREAD

**Issue by jcarter777** [aurieh/discord.nvim#20]
after uninstalling discord.vim in the usual way (removing from init.vim before running :PlugClean) I am getting this echoed at the bottom of my terminal:
```
no notification handler registered for "/home/jack/.local/share/nvim/plugged/discord.nvim/rplugin/python3/discord:autocmd:BufEnter:*"
no notification handler registered for "/home/jack/.local/share/nvim/plugged/discord.nvim/rplugin/python3/discord:autocmd:VimEnter:*"
Press ENTER or type command to continue
```
these files do not exist and the errors persist after restarting nvim, I have even reinstalled all of my plugins yet to no avail.

**Comment by ObserverOfTime** [comment]
Have you tried `:UpdateRemotePlugins`?

**Comment by jcarter777** [comment]
fixed, thanks
