### ISSUE TITLE
No notification handler registered

### ISSUE THREAD

**Issue by PlanetAaron** [aurieh/discord.nvim#21]
I install this plugin on MacOS Catalina 10.15.2 and neovim 0.4.3. However, I get this error
`no notification handler registered for "/Users/aaron/.vim/bundle/discord.nvim/rplugin/python3/discord:autocmd:VimEnter:*"`
I have googled around and have no idea how to fix this.

**Comment by aurieh** [comment]
Have you tried `:UpdateRemotePlugins`?

**Comment by samedamci** [comment]
The same issue

**Comment by Awlexus** [comment]
I'm having the same issue, even after running `:UpdateRemotePlugins` multiple times and even trying to restart

**Comment by aurieh** [comment]
Are you using any other RPC plugins alongside this one? If possible, please share a minimal `init.vim` you're able to reproduce this issue with, alongside versions of: Neovim, pynvim and your plugin manager, if you're using one.

**Comment by Awlexus** [comment]
Currently I can reproduce it with an ***empty*** `init.vim` file, even after deleting the `autoload` and `plugged` folder and reinstalling neovim and restarting... 
Does this plugin modify some files?

Some infos about my nvim
```bash
$ v --version                                                                                                <<<
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"
```

**Comment by aurieh** [comment]
No, it does not. Neovim, however, stores remote plugin listeners somewhere on the disk. Regardless, this feels very much like an issue with pynvim or Neovim itself. Would you mind creating an issue on their tracker?
