### ISSUE TITLE
Local discord client not found

### ISSUE THREAD

**Issue by jason-shepherd** [aurieh/discord.nvim#23]
When I open nvim, it says the discord client can't be found. Discord client is installed and running. I attempted to isolate the issue by only having only the discord.nvim plugin in my init.vim, but the issue remained.
![discordnvim](https://user-images.githubusercontent.com/19628380/72128109-c89e5f80-333f-11ea-9699-e7117d6aa674.PNG)

**Comment by aurieh** [comment]
Please check the paths in https://github.com/aurieh/discord.nvim/blob/59bf4835de6273750596b32a9bd30855d4ad67c7/rplugin/python3/discord/discord_rpc.py#L64-L65 and see if any one of them contains `discord-ipc-0` socket.

**Comment by jason-shepherd** [comment]
`        env_vars = ['XDG_RUNTIME_DIR', 'TMPDIR', 'TMP', 'TEMP']
        path = next((os.environ.get(path, None) for path in env_vars if path in os.environ), '/tmp')
`
This is what line 64 and 65 look like

**Comment by jason-shepherd** [comment]
I don't know if I checked the right directory or not, but I checked `C:\Users\myuser\AppData\Local\Temp` and nothing has the name discord-ipc-0. I also did a computer search with the same results. Hopefully that's what you meant.

**Comment by aurieh** [comment]
Oh, apologies, I probably should've asked about it first. This plugin is not supported on Windows.

**Comment by ObserverOfTime** [comment]
I can submit a pull request for Windows support if you want.

**Comment by aurieh** [comment]
@ObserverOfTime That'd be much appreciated, though I still do not wish to advertise support for NT/Windows.

**Comment by jason-shepherd** [comment]
There is already a fork that works for Windows by ananagame.

**Comment by ObserverOfTime** [comment]
What you're thinking of is an entirely different plugin. There is however a fork by [TTtie](https://github.com/TTtie/discord.nvim) that works on Windows, which I've also incorporated into my own [fork/rewrite](https://github.com/ObserverOfTime/discord.nvim/tree/refactored).

**Comment by tylerwolf35** [comment]
I have this issue as well on linux.

**Comment by tylerwolf35** [comment]
If you run into this issue using the Discord from snap you will need to change

 `        env_vars = ['XDG_RUNTIME_DIR', 'TMPDIR', 'TMP', 'TEMP']
        path = next((os.environ.get(path, None) for path in env_vars if path in os.environ), '/tmp')
        self.ipc_path = "{}/discord-ipc-0".format(path)
        self.client_id = client_id`

to

`        env_vars = ['XDG_RUNTIME_DIR', 'TMPDIR', 'TMP', 'TEMP']
        path = next((os.environ.get(path, None) for path in env_vars if path in os.environ), '/tmp')
        self.ipc_path = "{}/snap.discord/discord-ipc-0".format(path)
        self.client_id = client_id`

**Comment by DevepCoder** [comment]
> I don't know if I checked the right directory or not, but I checked `C:\Users\myuser\AppData\Local\Temp` and nothing has the name discord-ipc-0. I also did a computer search with the same results. Hopefully that's what you meant.

if you're using WSL
You can change it to /mnt/c/Users/myuser/AppData/Local/Temp

**Comment by LoadingBG** [comment]
What needs to be changed in the code in order for this plugin to work in WSL @DevepCoder ?

**Comment by ObserverOfTime** [comment]
Presumably nothing. Just set `TMPDIR` to `/mnt/c/Users/$USER/AppData/Local/Temp`.

**Comment by LoadingBG** [comment]
I still get `[Discord] Local Discord client not found` using your fork (`Plug 'ObserverOfTime/discord.nvim', {'do': ':UpdateRemotePlugins'}`) @ObserverOfTime .

**Comment by ObserverOfTime** [comment]
Like I said, set `TMPDIR` to `/mnt/c/Users/$USER/AppData/Local/Temp`.
If that doesn't work then, as I suspected, WSL cannot be supported.

**Comment by LoadingBG** [comment]
Yes, it didn't let me install the plugin without `:PlugClean` first. `$TMPDIR` is set to the proper location but there isn't `discord-ipc-0` in `Temp`.

**Comment by ObserverOfTime** [comment]
Then you're out of luck.

**Comment by LoadingBG** [comment]
`koukuno/wine-discord-ipc-bridge` fails on `make install` saying `~/.wine/drive_c/windows/winediscordicpbridge.exe: no such file or directory` even if I make it artificially.

**Comment by ObserverOfTime** [comment]
I didn't tell you to install. Just run `make CC=gcc` and see if the exe works.

**Comment by LoadingBG** [comment]
The output is `Not a wine installation?`

**Comment by ObserverOfTime** [comment]
So it won't work in WSL.
