### ISSUE TITLE
Discord RPC not showing up

### ISSUE THREAD

**Issue by ghost** [aurieh/discord.nvim#24]
Opening a file in neovim, and looking on discord, doesn't show discord presence.

**Comment by ObserverOfTime** [comment]
Is game activity enabled in Discord's settings?

**Comment by AVCADO** [comment]
`/usr/bin/nvim`?

**Comment by AVCADO** [comment]
Update: It is added in settings, yet it just says
"Playing a game:
     ?   nvim
   Just started playing"

**Comment by ObserverOfTime** [comment]
Remove what you added, restart Discord, and make sure *Display currently running game as a status message.* is checked.

**Comment by AVCADO** [comment]
Add it back?

**Comment by AVCADO** [comment]
![image](https://user-images.githubusercontent.com/56693327/81073515-5f71c780-8ead-11ea-9633-dd8ac1768096.png)
Here's what it looks like so far.

**Comment by ObserverOfTime** [comment]
What about the game activity settings tab?

**Comment by AVCADO** [comment]
![image](https://user-images.githubusercontent.com/56693327/81078617-12452400-8eb4-11ea-9e37-79b6d1410eb4.png)

**Comment by ObserverOfTime** [comment]
What's the output of `:checkhealth` in neovim?

**Comment by AVCADO** [comment]
![image](https://user-images.githubusercontent.com/56693327/81079801-9e0b8000-8eb5-11ea-9774-d18aeb68f1bd.png)

**Comment by ObserverOfTime** [comment]
There's your issue. You need to install `pynvim` for Python 3.

**Comment by AVCADO** [comment]
Alright, installed it. It still doesn't show up

**Comment by ObserverOfTime** [comment]
Run `:UpdateRemotePlugins` and restart neovim.

**Comment by AVCADO** [comment]
Same issue.

**Comment by ObserverOfTime** [comment]
Run `:checkhealth` again.

**Comment by AVCADO** [comment]
![image](https://user-images.githubusercontent.com/56693327/81082378-d06aac80-8eb8-11ea-9314-e37d6c5e064e.png)

**Comment by ObserverOfTime** [comment]
There should be a `health#discord#check` section. Are you sure you installed `discord.nvim`?

**Comment by AVCADO** [comment]
How would I install it if I haven't? (I just want to make sure)

**Comment by ObserverOfTime** [comment]
Read your plugin manager's docs.

**Comment by AVCADO** [comment]
![image](https://user-images.githubusercontent.com/56693327/81083289-ff355280-8eb9-11ea-9e58-3dcfdce99f68.png)
It should be installed because I put it in my `.vimrc`

**Comment by ObserverOfTime** [comment]
That's not how it works... Run `:PluginInstall`.

**Comment by AVCADO** [comment]
I did.

**Comment by AVCADO** [comment]
I ran them
`:UpdateRemotePlugins` gives me this:
![image](https://user-images.githubusercontent.com/56693327/81084211-335d4300-8ebb-11ea-808b-3e8f430332c9.png)

**Comment by ObserverOfTime** [comment]
Then it's not installed...

**Comment by Theodore-Robinson** [comment]
Please fix it ;(

**Comment by Theodore-Robinson** [comment]
Let me know if I can fill my discord client id manually
![image](https://user-images.githubusercontent.com/65941041/83965887-984ef300-a8d6-11ea-9e92-22f887717945.png)

**Comment by Theodore-Robinson** [comment]
:checkHealth returns this:
![image](https://user-images.githubusercontent.com/65941041/83965897-ba487580-a8d6-11ea-9648-75d2bcbad42f.png)

**Comment by aurieh** [comment]
@Theodore-Robinson likely not the same issue, however: are you using the desktop Discord client? If so, how did you install it: official tarball, distribution repositories, snap, flatpak, appimage maybe? Are you running the client in Firejail or some other kind of sandboxing solution?

**Comment by Theodore-Robinson** [comment]
I'm didn't do any of those crazy things to install discord
I just installed it normally with the installer at https://discord.com/download ([Installer here](https://discord.com/api/download?platform=win))

**Comment by ObserverOfTime** [comment]
Refer to https://github.com/aurieh/discord.nvim/issues/23#issuecomment-574181410.

**Comment by dannyhpy** [comment]
Hi! I don't see the Rich Presence on my profile
I ran :checkhealth, everything seems fine

When I close Discord, I have the message `[discord] local discord not found`
When I reopen it back, I don't have it anymore, so everything seems to be working but I don't see any rich presence on my profile

I don't think it requires Python 2, does it?
I'm on ArchLinux and I'm using the Discord Canary client

![image](https://user-images.githubusercontent.com/20782483/85304114-a9d5f480-b4ab-11ea-87cc-fc61e39c3ada.png)

**Comment by dannyhpy** [comment]
Nevermind it works! It seems .py is not 'whitelisted' or somewhat
![image](https://user-images.githubusercontent.com/20782483/85307781-9ed19300-b4b0-11ea-8e38-62e4a4ac556e.png)

In my opinion, every file format should be accepted by default and/or it should be mentionned in the **README.md** file

**Comment by ObserverOfTime** [comment]
Does it still work if you undo the edit?

**Comment by dannyhpy** [comment]
The last debug message I got is `[discord] ft: python` so it blocks here for some reason

**Comment by dannyhpy** [comment]
![image](https://user-images.githubusercontent.com/20782483/85311382-a5aed480-b4b5-11ea-8f9c-c05a84627c37.png)
![image](https://user-images.githubusercontent.com/20782483/85311410-ae9fa600-b4b5-11ea-97e4-3867d3a3e39b.png)

fts_whitelist is an empty list for me

**Comment by dannyhpy** [comment]
Ok, the on_vimenter part is never executed on my end
![image](https://user-images.githubusercontent.com/20782483/85312618-58336700-b4b7-11ea-8ab7-10ac6ae5e80f.png)
I replaced the default variables and they're still None once they pass the "check2"

**Comment by MinerChAI** [comment]
For me RPC doesn't display as well, but command `:DiscordUpdatePresence` works (checkhealth doesn't report any errors)

**Comment by dannyhpy** [comment]
Oh ok, yeah, it seems that **self.fts_blacklist** and **self.fts_whitelist** are not fullfilled directly 
When I switch to an another tab without my 'workaround', it updates well too

**Comment by TheRealDarkCoder** [comment]
Same here, Health Check has no issues
![image](https://user-images.githubusercontent.com/18534358/85401359-b6c21900-b57b-11ea-86a1-c368c17054dc.png)

**Comment by Gaarco** [comment]
Same issue as @TheRealDarkCoder but I didn't need to add NeoVim to games, I just have to use :DiscordUpdatePresence every time

**Comment by MinerChAI** [comment]
You don't need to add it to games, the plugin has an issue with startup. Use `autocmd VimEnter * DiscordUpdatePresence` as a workaround
@Gaarco @TheRealDarkCoder
