### ISSUE TITLE
Does not work when editing OCaml (.ml) files

### ISSUE THREAD

**Issue by rosalogia** [aurieh/discord.nvim#28]
discord.nvim works when editing Python files, but does not show anything at all when editing OCaml files. My guess is that this is because there isn't an icon readily available to be displayed when editing an OCaml file, but it would be nice if that wasn't really necessary. I added `\'ml',` to the whitelist in discord.vim, though this doesn't seem to have any effect.

**Comment by ObserverOfTime** [comment]
> My guess is that this is because there isn't an icon readily available to be displayed when editing an OCaml file, but it would be nice if that wasn't really necessary.

That's right and unfortunately it's necessary because that's how Discord RPC works.

**Comment by rosalogia** [comment]
I understand, thanks for your quick response :) Is this difficult to get fixed? Alternatively, are there any known work-arounds?

**Comment by ObserverOfTime** [comment]
It just needs to be added to the assets and the whitelist. Alternatively, you can make your own [RPC app](https://discord.com/developers/applications), add some icons, and replace the client ID and whitelist in `plugin/discord.vim`. Or, you can use [my fork](https://github.com/ObserverOfTime/discord.nvim) which supports OCaml.

**Comment by p00f** [comment]
Sorry for piggybacking this but can't a generic file icon be used for unknown filetypes?

**Comment by ObserverOfTime** [comment]
Yes, though it would still have to be added to the assets. Something like this should work:
```diff
--- i/rplugin/python3/discord/__init__.py
+++ w/rplugin/python3/discord/__init__.py
@@ -99,8 +99,10 @@ class DiscordPlugin(object):
             return
         ft = self.get_current_buf_var("&ft")
         self.log_debug('ft: {}'.format(ft))
-        if ft in self.fts_blacklist or ft not in self.fts_whitelist:
+        if ft in self.fts_blacklist:
             return
+        if ft not in self.fts_whitelist:
+            ft = 'unknown'
         workspace = self.get_workspace()
         if self.is_ratelimited(filename):
             if self.cbtimer:
```
