### ISSUE TITLE
Get an error running with Nvim with Spacevim, but can't read it.

### ISSUE THREAD

**Issue by codic12** [aurieh/discord.nvim#30]
On Linux, and using SpaceVim (with Neovim). Managed to install by adding `name = 'aurieh/discord.nvim'` into my init.toml file (in the CustomPlugins section, which uses dein behind the hood)... but when running nvim, for a second I get an error: `Error while processing /some/path/discord.vim:`. But there's nothing after the colon, and the error dissapears into thin air after a second (and i get my workspace). How should I go around resolving this? I have the Discord client installed and running from arch repos

**Comment by codic12** [comment]
got the full error, but i do have python3.
```

**Comment by codic12** [comment]
Fixed by installing the neovim module via pip! Now there's no error, but I still don't get rich presence

**Comment by ObserverOfTime** [comment]
See https://github.com/aurieh/discord.nvim/issues/24#issuecomment-653930100

**Comment by codic12** [comment]
Thanks @ObserverOfTime. Seems that `:autocmd VimEnter * DiscordUpdatePresence` does nothing (if ran as a command), and `:DiscordUpdatePresence`... doesn't exist?

**Comment by ObserverOfTime** [comment]
Did you run `:UpdateRemotePlugins`?

**Comment by codic12** [comment]
Nope, but I just did. I got this:
```
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/codic/.local/share/nvim/rplugin.vim
```

and restarted nvim, but still no rich presence

**Comment by ObserverOfTime** [comment]
That's because it's still not registered.

**Comment by codic12** [comment]
ah, how would i register it?
