### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by jedi2610** [aurieh/discord.nvim#36]
i installed the plugin but rich presence is not showing up and shows "pidfile exists". what am i doing wrong

**Comment by aurieh** [comment]
Please try removing `/tmp/dnvim_lock`.

**Comment by jedi2610** [comment]
@aurieh there's no such file in /tmp

**Comment by aurieh** [comment]
What about directories specified by `$TMPDIR`, `$TEMPDIR` and `$TMP` environment variables?

**Comment by jedi2610** [comment]
none everything is blank

**Comment by ObserverOfTime** [comment]
It's in `$XDG_RUNTIME_HOME`.

**Comment by jedi2610** [comment]
echoing $XDG_RUNTIME_HOME is blank again
