### ISSUE TITLE
Uninstalling Compeletly 

### ISSUE THREAD

**Issue by PouriDev** [aurieh/discord.nvim#39]
How can I uninstall it completely?? when I comment the `Plug 'aurieh/discord.nvim', { 'do': ':UpdateRemotePlugins'}` line in init.vim
and I do `:PlugClean` I get this error 
![image](https://user-images.githubusercontent.com/61497342/98205404-58576f00-1f4d-11eb-8e6c-028d7059917e.png)

**Comment by ObserverOfTime** [comment]
Duplicate of #20.

**Comment by PouriDev** [comment]
Thanks, got fixed .
