### ISSUE TITLE
[discord] pidfile exists

### ISSUE THREAD

**Issue by AND2797** [aurieh/discord.nvim#43]
Is this an error? Rich presence still doesn't show up on discord.

**Comment by aurieh** [comment]
nvim didn't exit cleanly, remove `/tmp/dnvim_lock`

**Comment by AND2797** [comment]
Thanks, that fixed that error! But now eventhough there are no errors, rich presence still doesn't seem to work. How can I figure out the issue? checkhealth reports all OK.

**Comment by aurieh** [comment]
Check Game Activity settings, enable "Display currently running game as status message" or something like that.
