### ISSUE TITLE
Does not work with tabs

### ISSUE THREAD

**Issue by parmort** [aurieh/discord.nvim#49]
Hi! Great project. It seems that the status does not update when switching tabs in vim. It works fine when opening and closing files, but switching between tabs does not update the status.

**Comment by aurieh** [comment]
Huh. From my testing, it should work with tabs as it makes use of the `BufEnter` event which, at least on my install, fires when switching tabs. Could you test by running `:au! BufEnter * echom "bufenter fired"`, then switching tabs?

**Comment by parmort** [comment]
Doing some more testing revealed that I have to reopen the status window to get the filename to update. There's nothing wrong with the autocommand. Sometimes, it does update without having to reopen the status window, but it takes a few seconds. It's just weird because opening and closing buffers immediately updates the status without having to reopen the status window.

**Comment by ObserverOfTime** [comment]
It probably takes a few seconds because there's a 15 second timeout to avoid being rate-limited.

**Comment by parmort** [comment]
Ah, that makes sense. Thank you!
