### ISSUE TITLE
Neovim icon won't show when editing unrecognized file type

### ISSUE THREAD

**Issue by ghost** [aurieh/discord.nvim#5]
Maybe it's missing the default state cover image?

![screenshot](https://my.mixtape.moe/qthfhx.png)

**Comment by deansheather** [comment]
The application has the default cover image set. It's been like this for a while. Still doesn't display anything when small icon name doesn't exist. This is a problem on Discord's end that we can get around by whitelisting types in this plugin.

![Default cover image](https://owo.whats-th.is/2cdcee.png)
