### ISSUE TITLE
Local client not Found on Mac M1

### ISSUE THREAD

**Issue by deevo-sage** [aurieh/discord.nvim#50]
cannot seem to work i've tried reinstalling discord, event installed it from brew,

This issue persists on every discord presence plugin....

**Comment by aurieh** [comment]
Unfortunately I do not have an M1 Mac to test on: could you check if any files starting with `discord-ipc-` exist in the `$TMPDIR` directory?

**Comment by ObserverOfTime** [comment]
discordjs/RPC#113 seems to have a solution of sorts.
The question is how do we implement that properly here?

What's the output of the following Python code?

```Python
print(__import__('tempfile').gettempdir())
```

**Comment by deevo-sage** [comment]
> [discordjs/RPC#113](https://github.com/discordjs/RPC/pull/113) seems to have a solution of sorts. The question is how do we implement that properly here?
> 
> What's the output of the following Python code?
> 
> ```python
> print(__import__('tempfile').gettempdir())
> ```

I got this as output 
```
/var/folders/32/2h86y69920q2gcd7s7zv1s940000gn/T
```

**Comment by ObserverOfTime** [comment]
Is `discord-ipc-0` in that folder?

**Comment by deevo-sage** [comment]
nope

**Comment by deevo-sage** [comment]
lots of com.apple stuff gql-language server and some yarn folders

**Comment by ObserverOfTime** [comment]
I'm assuming you've started Discord.

Does this script find the file?

```sh
find /private/var/folders -name "*discord-ipc*" || find /var/folders -name "*discord-ipc*"
```

**Comment by deevo-sage** [comment]
/var/folders/32/2h86y69920q2gcd7s7zv1s940000gn/T/discord-ipc-0

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/54073655/193353259-97932662-a31b-4c43-825f-41112220c874.png">

it found it in the same directory

**Comment by ObserverOfTime** [comment]
So had you not started Discord when you said "nope"? :thinking:

**Comment by deevo-sage** [comment]
it's been on for like last 5-6 hours, maybe wasn't able to see it in kitty, used warp and was clearer

**Comment by aurieh** [comment]
> Unfortunately I do not have an M1 Mac to test on: could you check if any files starting with `discord-ipc-` exist in the `$TMPDIR` directory?

I'd still like you to check this by getting the output of `python3 -c "import os, os.path; print(next((os.environ.get(path, None) for path in ['XDG_RUNTIME_DIR', 'TMPDIR', 'TMP', 'TEMP'] if path in os.environ), '/tmp'))"`. This is the logic used by the plugin to determine the directory of the IPC socket: it slightly differs from `tempfile.gettempdir()` (which we really should be using, but that is outside of this issue's scope).

**Comment by ObserverOfTime** [comment]
I wouldn't say it's outside of the issue's scope if it potentially fixes the issue.

**Comment by deevo-sage** [comment]
> > Unfortunately I do not have an M1 Mac to test on: could you check if any files starting with `discord-ipc-` exist in the `$TMPDIR` directory?
> 
> I'd still like you to check this by getting the output of `ls -A "$(python3 -c "import os, os.path; print(next((os.environ.get(path, None) for path in ['XDG_RUNTIME_DIR', 'TMPDIR', 'TMP', 'TEMP'] if path in os.environ), '/tmp'))")"`. This is the logic used by the plugin to determine the directory of the IPC socket: it slightly differs from `tempfile.gettempdir()` (which we really should be using, but that is outside of this issue's scope).

its finding discord-ipc-0

**Comment by ObserverOfTime** [comment]
Interesting. Why isn't it working then? :thinking:

**Comment by deevo-sage** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/54073655/193355372-fc3322f4-beb6-4ab0-9f77-57af74e17115.png">

no idea XD

**Comment by ObserverOfTime** [comment]
Maybe because you're using `sudo`?

**Comment by aurieh** [comment]
Indeed, the temporary directory for the root user is different from that of the regular user, which Discord is running as.

**Comment by deevo-sage** [comment]
loads of red stuff like this just to ignore i use sudo i guess XD
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/54073655/193355810-57699b93-79d9-49e8-aaf5-b8732fd820ee.png">

it's working without sudo acutally

**Comment by ObserverOfTime** [comment]
The file's in your home folder, just `chown` it.

**Comment by aurieh** [comment]
That particular error was most likely caused by the log file being created as root due to your previous use of `sudo`. As @ObserverOfTime already pointed out, you should be able to just `chown "$(id -u):"` it.

It is inadvisable to use your editor as root, consider `sudoedit` (or a macOS alternative) when you wish to edit files owned by another user.

**Comment by deevo-sage** [comment]
```
drwxr-xr-x@ 14 sidharthsahni  staff  448 Sep 15 00:10 nvim/
```
it's this right now what should i change it to root? ( i haven't used chown before )

**Comment by ObserverOfTime** [comment]
```sh
sudo chown -R $USER ~/.cache/nvim
```

**Comment by deevo-sage** [comment]
thanks <3
