### ISSUE TITLE
Add support for Crystal

### ISSUE THREAD

**Issue by yoru** [aurieh/discord.nvim#6]
Could you kindly upload the crystal logo?

PNG: https://crystal-lang.org/images/icon.png.

**Comment by aurieh** [comment]
It'll take a bit of time, as we manually edit each logo to include a white outline. I'll close this issue once it's done.

**Comment by aurieh** [comment]
![image](https://user-images.githubusercontent.com/18033264/35439309-d8840afa-02a2-11e8-8592-36aa7dc8eac0.png)
done
