### ISSUE TITLE
Add support for Nix

### ISSUE THREAD

**Issue by LightDiscord** [aurieh/discord.nvim#7]
Can you add Nix support ?

![PNG](https://nixos.org/logo/nixos-logo-only-hires.png)
(Url: https://nixos.org/logo/nixos-logo-only-hires.png)

**Comment by deansheather** [comment]
Sure, I'll add it to the application this weekend.

**Comment by deansheather** [comment]
Added small `nix` asset to the Discord application for Neovim. Please close @aurieh.

![nix icon](https://owo.whats-th.is/7ffe2f.png)
